### ISSUE TITLE
Webserver & Middleware system integrations

### ISSUE THREAD

**Issue by deadtrickster** [deadtrickster/prometheus.erl#60]
(Re)Write using [prometheus_httpd](https://github.com/deadtrickster/prometheus_httpd):

- [ ] [Elli](https://github.com/elli-lib/elli) - [Elli Prometheus](https://github.com/elli-lib/elli_prometheus)
- [ ] [Plugs](https://github.com/elixir-lang/plug) - [Prometheus Plugs](https://github.com/deadtrickster/prometheus-plugs)
- [ ] [Raxx](https://github.com/CrowdHailer/raxx) - [Prometheus Raxx](https://github.com/deadtrickster/prometheus-raxx)
- [x] [Inets](http://erlang.org/doc/apps/inets/http_server.html) - [Prometheus HTTPD](https://github.com/deadtrickster/prometheus_httpd)
- [ ] [Cowboy](https://github.com/ninenines/cowboy) - [Prometheus Cowboy](https://github.com/deadtrickster/prometheus_cowboy)
- [ ] [Yaws](https://github.com/klacke/yaws) - [Prometheus Yaws](https://github.com/deadtrickster/prometheus_yaws)
- [ ] [Webmachine](https://github.com/webmachine/webmachine) - [Prometheus Webmachine](https://github.com/deadtrickster/prometheus_webmachine)
- [ ] [Mochiweb](https://github.com/mochi/mochiweb) - [Prometheus Mochiweb](https://github.com/deadtrickster/prometheus_mochiweb)

**Comment by deadtrickster** [comment]
https://github.com/deadtrickster/prometheus.erl/wiki/Webserver-&-Middleware-system-integrations
